* General functionality

The board is equipped with dimmers for LEDs, and has leds in several white temperatures. The goal is to be able to drive the dimming and the color temperature separately through DMX, while the firmware will do the correct "mixing" of warm and cold light to get to the wanted temperature.

* Hardware Board

This library supports several boards, all in the STC8H family (http://www.stcmicro.com/datasheet/STC8H-en.pdf)

The boards all use the processor STC8H1K16-36I-LQFP32
It exists in several version, with 3, 4, 5 or 6 PWM outputs.

** General setup
Board clock: 24MHz
UART: 250000 baud
Memory:

** Pinout
The different boards have slightly different PCBs, and so the input and outputs are not mapped to the same ports on all.

For the library to be more overseeable, make the mapping in 2 steps:
 - produce a file that contains the name of the board, and maps the actual ports (P1.0, P1.1 etc.) to logical names (DIP_1, DIP_2, PWM_1, RxD, TxD, etc.)
 - have the code that does the setup use these logical names only (so that code does not change too much).

Here are the boards and their pin out.

*** Board MINI-DMX-3CH-V1.2

| pin | port      | function             |
|-----+-----------+----------------------|
|   1 | P1.0      | PWM_3                |
|   2 | P1.1      |                      |
|   3 | P1.2      | PWM_2                |
|   4 | P1.3      |                      |
|   5 | P1.4      | PWM_1                |
|   6 | P1.5      | AGnd                 |
|   7 | P1.6      | ADC_Vref+            |
|   8 | P1.7      | AVcc                 |
|-----+-----------+----------------------|
|   9 | P5.4      |                      |
|  10 | Vcc/AVcc  |                      |
|  11 | ADC_VRef+ |                      |
|  12 | Gnd/AGnd  |                      |
|  13 | P3.0      | RxD (prog connector) |
|  14 | P3.1      | TxD (prog connector) |
|  15 | P3.2      | DMX_LED              |
|  16 | P3.3      | DIP_1                |
|-----+-----------+----------------------|
|  17 | P3.4      | DIP_2                |
|  18 | P3.5      | DIP_3                |
|  19 | P3.6      | DIP_4                |
|  20 | P3.7      | DIP_5                |
|  21 | P2.0      |                      |
|  22 | P2.1      |                      |
|  23 | P2.2      |                      |
|  24 | P2.3      |                      |
|-----+-----------+----------------------|
|  25 | P2.4      | DIP_6                |
|  26 | P2.5      | DIP_7                |
|  27 | P2.6      | DIP_8                |
|  28 | P2.7      | DIP_9                |
|  29 | P0.0      | DIP_10_MODE          |
|  30 | P0.1      |                      |
|  31 | P0.2      |                      |
|  32 | P0.3      |                      |

*** Board WS-DMX-3CH-BAN-Rev-4.6

Do as if it was different (i.e. produce files) but use the same mapping MINI-DMX-3CH-V1.2 for the time being, I have not checked with the physical board yet.

* DMX
The software will expose several modes to help with driving the R/G/B channels. Modes are a collection of channels.

** Channels

- #1: general dimmer (coarse)
- #2: general dimmer (fine)
- #3: color temperature (coarse)
- #4: color temperature (fine)
- #5: strobe mode (no strobe, flashing, lightning)
- #6: strobe speed (slow -> fast)

** Modes

We can handle 2 modes, depending on DIP_10 (the mode bit). This is reflected in the code that we handle a different number of DMX addresses.
Note that this dip can be changed live, so the number of used adresses needs to be dynamic.

*** Simple mode (4 channels)
This exposes these channels:
1. general dimmer (coarse)
2. color temperature (coarse)
3. strobe mode
4. strobe speed

*** Full mode (6 channels)
This exposes these channels:
1. general dimmer (coarse)
2. general dimmer (fine)
3. color temperature (coarse)
4. color temperature (fine)
5. strobe mode
6. strobe speed

* Software
** Development Environment
*** Dev tools
I use only open-source tools. do not suggest any non-open tools.
Building: sdcc on platformio
Flashing: stcgal
Debugging: printf along with a terminal

*** Global Coding Rules
**** Functionality
- Never use floating point (strict constraint).
- All DMX buffer logic must reside in ~dmx.c~.

**** Style
Always use the '1TBS' (One True Brace Style) for C code.
  - Braces on the same line as 'if', 'while', 'for'.
  - Use 2 spaces for indentation (no tabs).
  - Keep the 'else' on the same line as the closing brace: '} else {'.
Do not try to fix style yourself at the end, I will do it.
** Code Structure

The code is split into files that have a *.h and a *.c file. These are the responsibilities of each file:

- stc8h.h / config.h
  Some specific definitions for the CPU.
  Config for the system clock and baud rate.

- boards/*.h
  Contains the mapping from hardware I/O pins to logical names, one file for each supported board.
  also contains the number of PWM channels that are in the hardware of the board.

- uart.h / uart.c
  reads the DMX frames, and deals with interrupts, DMA, etc. It reads the full frame, or at least all that comes through the wire (when some frames get clipped).
  Contains the volatile data buffer, as well as a way to check if there is a new frame.

- dip.h / dip.c
  interfaces to the setup of the board, reads the DIP switches to get the mode and the DMS address.

- dmx.h / dmx.c
  Defines the modes (as an enum) and the =DmxState= struct that has the values for all possible channels, possibly 16 bit values.
  It gets the address dip.h and the data from uart.h and selects the subset of values which are the data for the current device.
  It contains the parser for this data into the  DmxState structure.

- pwm.h / pwm.c
  Sets up the PWM machinery and pins, and provides functions to set each channel to the correct level with a 16 bit value.
  It also defines a pwmState struct that contains as many channels as are configured for the board.
  the pwmUpdate() takes such a structure and sets all relevant pwm to the duty cycle in that struct.

- color.h / color.c
  Contains the mapping from a particular color temperature (as represented in the DmxState struct) and its mapping to the set of LEDs that are hooked up the board. This computes which mix of the several LEDs are needed to get a particular color temperature.

- main.c
  This sets up the subsystems, then implements the global loop as well as the DMX led blinking logic.

- numeric.h
  Contains some basic math functions.
